name: Simple Test Artifact Upload

on:
  push:
    branches:
      - main

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create a test file
        run: |
          mkdir -p output
          echo "Hello from GitHub Actions!" > output/hello.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-artifact
          path: output/hello.txt
